### ISSUE TITLE
关于建议使用组织来管理r-nacos 项目，正在推进中

### ISSUE THREAD

**Issue by heqingpan** [r-nacos/rnacos#38]
我个人之前对怎么管理开源项目其实是没有经验的，在了解组织管理的更合适多人共同协作功能后，基本认同这个建议。

目前r-nacos组织已经申请下来，后继的步骤还在探索中。

等完全迁移好之后，会在新组织项目中推进项目开发工作；同时在本仓库readme 加对应说明，并对本仓库动静存档。

（没关闭本 issue 前说明没有迁移完成，还会在本仓库开发。）

**Comment by Liangdi** [comment]
仓库可以直接转移阿，不需要存单吧

**Comment by heqingpan** [comment]
> 仓库可以直接转移阿，不需要存单吧

确实可以直接转移。就是里面的文档地址要做下调整；
issues要重新维护，

**Comment by Liangdi** [comment]
> > 仓库可以直接转移阿，不需要存单吧
> 
> 确实可以直接转移。 就是里面的项目文档地址要做下调整，issu

我自己没有实操过， 不过
https://github.com/zino-rs/zino
从 https://github.com/photino/zino  转移过去的  star , issue 也是一起过的

**Comment by heqingpan** [comment]
> > > 仓库可以直接转移阿，不需要存单吧
> > 
> > 
> > 确实可以直接转移。 就是里面的项目文档地址要做下调整，issu
> 
> 我自己没有实操过， 不过 https://github.com/zino-rs/zino 从 https://github.com/photino/zino 转移过去的 star , issue 也是一起过的

那就奇怪了。
我操作了之后star,issue 是空的，可能是我操作方式不对，我再看看。

**Comment by heqingpan** [comment]
今天抽空查了下迁移文档，已完成迁移
